"use client";

import { useClarityStore } from "@/lib/store";
import { AlertCircle, CheckCircle, AlertTriangle } from "lucide-react";

export function ReportPanel() {
  const { analysis, selectedSentenceIndex, setSelectedSentenceIndex } =
    useClarityStore();

  if (!analysis) {
    return (
      <div className="flex flex-col h-full bg-card items-center justify-center p-6 text-center">
        <p className="text-sm text-muted-foreground">
          No report data available. Please upload an image first.
        </p>
      </div>
    );
  }

  const getStatusIcon = (confidence: number) => {
    if (confidence >= 0.8)
      return <CheckCircle size={16} className="text-accent" />;
    if (confidence >= 0.5)
      return <AlertTriangle size={16} className="text-warning" />;
    return <AlertCircle size={16} className="text-destructive" />;
  };

  const getStatusBadge = (confidence: number) => {
    if (confidence >= 0.8) return "bg-accent/10 text-accent border-accent/20";
    if (confidence >= 0.5)
      return "bg-warning/10 text-warning border-warning/20";
    return "bg-destructive/10 text-destructive border-destructive/20";
  };

  return (
    <div className="flex flex-col h-full bg-card animate-in fade-in duration-500">
      <div className="flex-1 overflow-auto scrollbar-thin">
        {/* Report Section */}
        <div className="border-b border-border">
          <div className="px-6 py-4 border-b border-border bg-muted/20 backdrop-blur-sm sticky top-0 z-10">
            <h2 className="text-lg font-bold text-foreground">
              Radiology Report
            </h2>
            <p className="text-[10px] uppercase tracking-widest text-muted-foreground mt-1">
              Generated by BioViL-L Model
            </p>
          </div>

          <div className="p-6 space-y-3">
            {analysis.sentences?.map((sentenceObj, idx) => (
              <button
                key={idx}
                onClick={() => setSelectedSentenceIndex(idx)}
                className={`w-full text-left p-4 rounded-xl border transition-all duration-200 group relative ${
                  selectedSentenceIndex === idx
                    ? "border-accent bg-accent/5 shadow-sm ring-1 ring-accent/20"
                    : "border-border hover:border-accent/30 hover:bg-secondary/50"
                }`}
              >
                <div className="flex gap-4">
                  <span
                    className={`flex-shrink-0 flex items-center justify-center w-6 h-6 rounded-full text-[10px] font-black transition-colors ${
                      selectedSentenceIndex === idx
                        ? "bg-accent text-white"
                        : "bg-muted text-muted-foreground group-hover:bg-accent/10 group-hover:text-accent"
                    }`}
                  >
                    {idx + 1}
                  </span>
                  <p
                    className={`text-sm leading-relaxed transition-colors ${
                      selectedSentenceIndex === idx
                        ? "text-foreground font-medium"
                        : "text-foreground/80 group-hover:text-foreground"
                    }`}
                  >
                    {sentenceObj.sentence_text}
                  </p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Selected Sentence Analysis Detail */}
        {selectedSentenceIndex !== null && (
          <div className="p-6 space-y-6 animate-in slide-in-from-bottom-2 duration-300">
            <div className="flex items-center justify-between">
              <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground">
                Grounded Analysis
              </h3>
              <div
                className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full border text-[10px] font-bold uppercase tracking-wider ${getStatusBadge(
                  0.9, // Placeholder confidence
                )}`}
              >
                {getStatusIcon(0.9)}
                Verified Logic
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="p-4 rounded-xl bg-secondary/30 border border-border/50">
                <p className="text-[10px] font-bold text-muted-foreground uppercase mb-1">
                  Focus Region
                </p>
                <p className="text-sm font-black text-foreground">
                  Spatial Attention
                </p>
              </div>
              <div className="p-4 rounded-xl bg-secondary/30 border border-border/50">
                <p className="text-[10px] font-bold text-muted-foreground uppercase mb-1">
                  Model Weight
                </p>
                <p className="text-sm font-black text-foreground">High</p>
              </div>
            </div>

            <div className="space-y-3">
              <p className="text-xs text-muted-foreground leading-relaxed">
                The heatmap in the visualizer highlights the specific regions of
                the radiograph the model focused on when generating this
                sentence.
              </p>
            </div>
          </div>
        )}
      </div>

      <div className="p-4 border-t border-border bg-muted/20">
        <p className="text-[9px] text-center text-muted-foreground font-medium leading-relaxed">
          AI-generated reports are for research purposes and should be verified
          by a board-certified radiologist.
        </p>
      </div>
    </div>
  );
}
